name: Release

on:
  push:
    # tags:
    #   - "*"

jobs:
  publish:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, macos]

        include:
          - name: linux
            os: ubuntu-latest
            executable: yap
            artifact_name: target/release/yap
            asset_name: yap-Linux-x86_64.zip

          - name: macos
            os: macos-latest
            executable: yap
            artifact_name: target/release/yap
            asset_name: yap-MacOS-x86_64.zip

    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: cargo build --release && mv ${{ matrix.artifact_name }} .
      
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: ${{ matrix.executable }}
          filename: ${{ matrix.asset_name }}

      - name: Upload Release
        # uses: "marvinpinto/action-automatic-releases@latest"
        # with:
        #   repo_token: "${{ secrets.GITHUB_TOKEN }}"
        #   files: ${{ matrix.asset_name }}
        # 
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          gh release upload --clobber ${{ tag_name }} ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION:  ${{ needs.draft_release.outputs.tag_name }}
